class Pet < ApplicationRecord
  belongs_to :user

  SIZE_KG = ["Mini: 0-5kg", "Pequeno: 5-10kg", "Médio: 10-20kg", "Grande: 20-40kg", "Gigante: +40kg"]
  BREED = ["Akita",
  "Basset hound",
  "Beagle",
  "Bichon frisé",
  "Boiadeiro australiano",
  "Border collie",
  "Boston terrier",
  "Boxer",
  "Buldogue francês",
  "Buldogue inglês",
  "Bull terrier",
  "Cane corso",
  "Cavalier king charles spaniel",
  "Chihuahua",
  "Chow chow",
  "Cocker spaniel inglês",
  "Dachshund",
  "Dálmata",
  "Doberman",
  "Dogo argentino",
  "Dogue alemão",
  "Fila brasileiro",
  "Golden retriever",
  "Husky siberiano",
  "Jack russell terrier",
  "Labrador retriever",
  "Lhasa apso",
  "Lulu da pomerânia",
  "Maltês",
  "Mastiff inglês",
  "Mastim tibetano",
  "Pastor alemão",
  "Pastor australiano",
  "Pastor de Shetland",
  "Pequinês",
  "Pinscher",
  "Pit bull",
  "Poodle",
  "Pug",
  "Rottweiler",
  "Schnauzer",
  "Shar-pei",
  "Shiba",
  "Shih tzu",
  "Staffordshire bull terrier",
  "Weimaraner",
  "Yorkshire",
  "SRD",
  "Outra"]
end
